var FeedViewer={initialise:function(){FeedViewer.initialiseAddFeeds();FeedViewer.initialiseMyFeeds();YoutubeManager.initialiseYoutubeFeeds();ReaderViewer.initialise();ReaderViewer.initialiseHeadlineView();GoogleReader.initialise();jQTubeUtil.init({key:"AI39si7Br60Mhmvnb0iGT_DckKttQdd_8ghDOs_UQIcmb3wDhwAnZlkPe9lqp1llOv9rZNGqdKcdP8BdHRDOMaY4Mu0Xh3op9g",orderby:"viewCount",time:"this_month",maxResults:5});$("#tomyfeedsbtn").click(function(){switchToMyFeeds()});$("#tomyfeedsbtn2").click(function(){switchToMyFeeds()});
$(".toaddfeedsbtn").click(function(){modes.switchToMode(0)});$("#addFeedsForm").submit(function(){var a=$(".filter .selected");if("youtube"==$(a).attr("data-value"))YoutubeManager.getVideos($(this).find("input")[1].value);else{var b=encodeURI($(this).find("input")[1].value);/(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?/.test(b)?DbManager.checkSubscription(b,function(a){1!=a?($("#loadingurl").css("opacity",1),FeedViewer.sendForSubscription(b,null)):($("#loadingurl").css("opacity",
0),showMessage("<b>You are already subscribed to this feed. Go to Myfeeds page to view the feeds.</b>"))}):($("#loadingurl").css("opacity",0),$("#searchbox").find("input")[1].value="",showMessage("<b>Please Enter a Valid Url!!!</b>"))}})},initialiseAddFeeds:function(){FeedViewer.renderAddFeeds();YoutubeManager.initYoutubeInAddfeeds();YoutubeManager.suggestionClick();$(".grimg li").hover(function(){var a=$(this),b=$(".filter .selected");$(".fdname",this).css("text-decoration","underline");"youtube"!=
$(b).attr("data-value")&&(b=$(this).attr("data-id"),DbManager.checkSubscription(b,function(b){1==b?$(".caption",a).fadeOut(100,function(){$(this).html("Click to Unsubscribe").css("margin-top","-55px")}).stop(!0,!0).fadeIn(50):$(".caption",a).html()=="Click me to subscribe to "+$("img",a).attr("title")&&($(".caption",a).stop(!0,!0).animate({opacity:1,"margin-top":-60},50),$("img",a).stop(!0,!0).animate({opacity:0.1},100))}))},function(){var a=$(this),b=$(".filter .selected");$(".fdname",this).css("text-decoration",
"none");"youtube"!=$(b).attr("data-value")&&(b=$(this).attr("data-id"),DbManager.checkSubscription(b,function(b){1==b?$(".caption",a).fadeOut(100,function(){$(this).html("You are subscribed to "+$(this).parent().find(".feedimage").attr("title")+'<br><img class="subscbdimg" src="img/done.png">').css("margin-top","-60px")}).stop(0,!0,!0).fadeIn(50):$(".caption",a).html()=="Click me to subscribe to "+$("img",a).attr("title")&&($(".caption",a).stop(0,!0,!0).animate({opacity:0},50),$("img",a).stop(0,!0,
!0).animate({opacity:1},200))}))});$(".grimg li").live("click",function(){var a=$(this),b=$(this).find(".caption"),c=$(".filter .selected");"youtube"!=$(c).attr("data-value")&&("Click to Unsubscribe"!=b.html()?(b=$(this).attr("data-id"),$(".caption",this).html('<img src="img/addfeed.gif"><br>Subscribing. Please Wait...'),$(".caption",this).animate({opacity:1,"margin-top":-80},50),$("img",this).animate({opacity:0.1},200),$(".caption img",this).animate({opacity:1},0),FeedViewer.sendForSubscription(b,
a)):(url=$(this).attr("data-id"),Reader.unsubscribe(url,function(){FeedViewer.renderMyFeeds();showUnsubscribedFeed(a)})))});$(".filter a").live("click",function(){if("selected"!=$(this).attr("class")){$(".filter a").removeClass("selected");var a=$(this).attr("class");$(this).addClass("selected");"youtube"==$(this).attr("data-value")?($("#addFeedsForm img").attr("src","img/search-dark.png"),$("#error-message").html("Search in the SearchBox above for Youtube Videos."),$("#addFeedsForm").find("span").text("Search Youtube:")):
($("#addFeedsForm img").attr("src","img/add.png"),$("#error-message").html("Click on the feed from the categories given below or enter the URL of the desired feed of your wish"),$("#addFeedsForm").find("span").text("Add Feeds:"));a=-950*a+40;$("#container").animate({"margin-left":a},300)}});YoutubeManager.captionAnim();$("#feedback").click(function(){pokki.openURLInDefaultBrowser("http://www.codeblues.in/softwares/feedreader.php")})},initialiseMyFeeds:function(){FeedViewer.renderMyFeeds();$(".feedl").live("click",
function(a){a.stopPropagation();$("#loadingScreen").css("visibility","visible").css("display","block");a=$(this).attr("rel");Reader.getFeedContent(a,null,ReaderViewer.showFetchError)});$(".unsub").live("mouseenter",function(){$(this).css("opacity","1")});$(".unsub").live("mouseleave",function(){$(this).css("opacity","0.3")});$(".unsub").live("click",function(a){a.stopPropagation();modes.currentmode==modes.myFeedsMode&&(url=$(this).parent().attr("rel"));var b=$(this);Reader.unsubscribe($(this).parent().attr("rel"),
function(){$(b).parent().hide("fast",function(){$(this).parent().remove()});$("#stage li").each(function(){$(this).attr("data-id")==url&&showUnsubscribedFeed($(this))})})});$(".readmarker").live("click",function(a){var b=$(this);a.stopPropagation();a=$(this).parent().attr("rel");Reader.markAllAsRead(a,function(){$(b).find("img").attr("src","img/marked2.png");$(b).parent().find(".readunread").html("0")})})},renderAddFeeds:function(){DbManager.getSubscriptionIds(function(a){null!=a?$("#stage li").each(function(){-1!=
$.inArray($(this).attr("data-id"),a)?showSubscribedFeed($(this)):showUnsubscribedFeed($(this))}):$("#stage li").each(function(){$(".caption",this).html("Click me to subscribe to "+$("img",this).attr("title"))})})},renderMyFeeds:function(){$("#myfeedsdiv .myfeedlist").empty();DbManager.getSubscriptions(function(a){if(null!=a)for(var b=0;b<a.length;b++)if(a[b]){var c=a[b].title;if(!0==GoogleReader.hasAuth())var e=a[b].unreadCount;var f=getDomain(a[b].url)+"/favicon.ico",g=Math.floor(5*Math.random());
if(!0==GoogleReader.hasAuth())var d="<div class='readunread'>"+e+"</div>",d=0==e?d+"<div class='readmarker'><img src='img/marked2.png'></div></div></li>":d+"<div class='readmarker'><img src='img/notify.gif'></div></div></li>";else d="";$("#myfeedsdiv .myfeedlist").append("<li><div class='feedl color"+g+"' rel = "+a[b].url+" ><div class='unsub'></div><img class='faviconimg' src='"+f+"'/><p>"+c.substring(0,25)+"</p>"+d)}else b++});$(".faviconimg").error(function(){$(this).attr("src","img/defaultfavicon.png")})},
showSuccessfulSubscription:function(a,b,c){null!=c?showSubscribedFeed(c):($("#searchbox").find("input")[1].value="",$("#stage li").each(function(){$(this).attr("data-id")==b&&showSubscribedFeed($(this))}));$("#loadingurl").css("opacity",0);showMessage("<b>Successfully subscribed to "+a+"</b>")},searchMyFeeds:function(a){a=a.toLowerCase();null==a||""==a?$("#myfeedsdiv .feedl").each(function(){$(this).fadeIn()}):$("#myfeedsdiv .feedl").each(function(){-1==$(this).text().toLowerCase().indexOf(a)?$(this).fadeOut("fast"):
$(this).fadeIn("slow")})},updateFeedCount:function(){$(".feedl").each(function(){var a=$(this);DbManager.getUnreadCount($(this).attr("rel"),function(b){$(a).find(".readunread").html(b);0==b?$(a).find(".readmarker").find("img").attr("src","img/marked2.png"):$(a).find(".readmarker").find("img").attr("src","img/notify.gif")})})},sendForSubscription:function(a,b){GoogleReader.getFeedContent(a,20,"","",function(a){a.id=a.id.substr(5);Reader.subscribe(a);FeedViewer.showSuccessfulSubscription(a.title,a.id,
b);FeedViewer.renderMyFeeds()},function(a){$("#searchbox").find("input:text").val("");$("#loadingurl").css("opacity",0);"Not Found"==a?showMessage("<strong>Sorry, We could not find feeds at this url.</strong>"):showMessage("<strong>Error Subscribing to Feed. Please try again later.</strong>");b&&$(".caption",b).html("Error Subscribing to "+$(b).find("img").attr("title")).animate({opacity:1,"margin-top":-60},200).delay(2E3).fadeOut(200).fadeIn(0,function(){$(".caption",b).html();showUnsubscribedFeed(b)})})}};
