var GoogleReader;
GoogleReader={access_token:"",api_token:"",refresh_token:"",redirect_uri:"http://www.codeblues.in",client:"scroll",retries:0,tags:{like:"user/-/state/com.google/like",label:"user/-/label/",star:"user/-/state/com.google/starred",read:"user/-/state/com.google/read",fresh:"user/-/state/com.google/fresh",share:"user/-/state/com.google/broadcast","kept-unread":"user/-/state/com.google/kept-unread","reading-list":"user/-/state/com.google/reading-list"},SUBSCRIPTION_LIST_URL:"http://www.google.com/reader/api/0/subscription/list",SUBSCRIPTION_EDIT_URL:"http://www.google.com/reader/api/0/subscription/edit",
API_TOKEN_URL:"http://www.google.com/reader/api/0/token",USER_INFO_URL:"http://www.google.com/reader/api/0/user-info",MARK_ALL_READ_URL:"http://www.google.com/reader/api/0/mark-all-as-read",EDIT_TAG_URL:"http://www.google.com/reader/api/0/edit-tag",UNREAD_COUNT_URL:"http://www.google.com/reader/api/0/unread-count",FEED_CONTENT_URL:"http://www.google.com/reader/api/0/stream/contents/feed/",SUBS_CHECK_URL:"http://www.google.com/reader/api/0/subscribed",ITEM_CONTENT_URL:"http://www.google.com/reader.stream/items/contents",
initialise:function(){this.access_token=window.localStorage.getItem("access_token");this.refresh_token=window.localStorage.getItem("refresh_token");this.access_token&&this.refresh_token&&this.getApiToken()},loginViaOauth:function(a){var b="https://accounts.google.com/o/oauth2/auth?scope=http://www.google.com/reader/api/&response_type=code&redirect_uri="+this.redirect_uri+"&client_id=241567971408-oqc99hgb5al8kc7pl1h05iejl65r30ft.apps.googleusercontent.com&access_type=offline&approval_prompt=force",
b=encodeURI(b);pokki.clearWebSheetCookies();pokki.showWebSheet(b,512,400,function(c){if(0==c.indexOf(GoogleReader.redirect_uri)){for(var b={},c=c.split("?")[1],e=/([^&=]+)=([^&]*)/g;c=e.exec(c);){b[decodeURIComponent(c[1])]=decodeURIComponent(c[2]);b="code="+b[decodeURIComponent(c[1])]+"&client_id=241567971408-oqc99hgb5al8kc7pl1h05iejl65r30ft.apps.googleusercontent.com&client_secret=HY11TSTGm7ydZrnkfwTHsUyK&redirect_uri="+GoogleReader.redirect_uri+"&scope=&grant_type=authorization_code";$.ajax({type:"POST",
url:"https://accounts.google.com/o/oauth2/token",data:b,dataType:"json",success:function(b){GoogleReader.setTokens(b.access_token,b.refresh_token,a)},error:function(){}});break}pokki.hideWebSheet()}else return!0},function(b){pokki.hideWebSheet();a("Error : "+b)})},getApiToken:function(){$.get(GoogleReader.API_TOKEN_URL+"?access_token="+GoogleReader.access_token,function(a){GoogleReader.api_token=a})},refreshAccessToken:function(a){$.ajax({type:"POST",url:"https://accounts.google.com/o/oauth2/token",
data:"client_id=241567971408-oqc99hgb5al8kc7pl1h05iejl65r30ft.apps.googleusercontent.com&client_secret=HY11TSTGm7ydZrnkfwTHsUyK&refresh_token="+this.refresh_token+"&grant_type=refresh_token",dataType:"json",success:function(b){GoogleReader.setTokens(b.access_token,"",a)},error:function(){}})},setTokens:function(a,b,c){GoogleReader.access_token=a;this.getApiToken();window.localStorage.setItem("access_token",a);b&&0<b.length&&(window.localStorage.setItem("refresh_token",b),GoogleReader.refresh_token=
b);c("OK")},getUserInfo:function(a){getData(this.USER_INFO_URL,null,a)},hasAuth:function(){return window.localStorage.getItem("refresh_token")&&""!=window.localStorage.getItem("refresh_token")?!0:!1},logout:function(){window.localStorage.setItem("isSyncOn","false");window.localStorage.setItem("access_token","");window.localStorage.setItem("refresh_token","");this.refresh_token=this.access_token=""},getSubscriptionList:function(a){this.getData(GoogleReader.SUBSCRIPTION_LIST_URL,"output=json&access_token="+
this.access_token,a)},getFeedContent:function(a,b,c,d,e,f){a=encodeURIComponent(a);d="r=n&access_token="+GoogleReader.access_token+"&client="+this.client+"&c="+d;d=null!=c&&0!=c.length&&GoogleReader.hasAuth()?d+("&xt="+GoogleReader.tags[c]):d+("&n="+b);this.getData(GoogleReader.FEED_CONTENT_URL+a,d,e,f)},getItemContent:function(){this.postData(this.ITEM_CONTENT_URL+"?freshness=false&client="+this.client,function(){})},checkIfSubscribed:function(a,b){this.getData(GoogleReader.SUBS_CHECK_URL,"s=feed/"+
a,b)},subscribe:function(a,b,c,d){this.postData(this.SUBSCRIPTION_EDIT_URL,"s=feed/"+a+"&ac=subscribe&T="+GoogleReader.api_token,d)},unsubscribe:function(a,b){this.postData(this.SUBSCRIPTION_EDIT_URL,"s=feed/"+a+"&ac=unsubscribe&T="+this.api_token,b)},addItemTag:function(a,b,c,d){a=encodeURIComponent(a);this.postData(this.EDIT_TAG_URL,"s=feed/"+a+"&ac=edit&async=true&a="+this.tags[c]+"&i="+b+"&T="+this.api_token,d)},removeItemTag:function(a,b,c,d){a=encodeURIComponent(a);this.postData(this.EDIT_TAG_URL,
"s=feed/"+a+"&ac=edit&async=true&r="+this.tags[c]+"&i="+b+"&T="+this.api_token,d)},editItemTag:function(a,b,c,d,e){a=encodeURIComponent(a);this.postData(this.EDIT_TAG_URL,"s=feed/"+a+"&ac=edit&async=true&a="+this.tags[c]+"&r="+this.tags[d]+"&i="+b+"&T="+this.api_token,e)},getUnreadCount:function(a){this.getData(this.UNREAD_COUNT_URL,"output=json&output=json&access_token="+this.access_token+"&client="+this.client,a,"json")},markAllAsRead:function(a,b){this.postData(this.MARK_ALL_READ_URL+"?client="+
GoogleReader.client,"s=feed/"+a+"&T="+GoogleReader.api_token,b)},getData:function(a,b,c,d){$.ajax({method:"get",url:a,data:b,dataType:"json",success:c,timeout:15E3,error:function(e,f,g){401==e.status||400==e.status?5<GoogleReader.retries?d&&d():(GoogleReader.retries++,GoogleReader.refreshAccessToken(function(d){"OK"==d&&(GoogleReader.retries=0,GoogleReader.getData(a,GoogleReader.updateData(b),c))})):d&&d(g)}})},postData:function(a,b,c){$.ajax({type:"POST",url:a,data:b,beforeSend:function(a){a.setRequestHeader("Authorization",
"Bearer "+GoogleReader.access_token)},success:function(){c&&c()},timeout:15E3,statusCode:{401:function(){5<GoogleReader.retries||(GoogleReader.retries++,GoogleReader.refreshAccessToken(function(d){"OK"==d&&(GoogleReader.retries=0,GoogleReader.postData(a,GoogleReader.updateData(b),c))}))}},error:function(){}})},updateData:function(a){var b=[],b=a.split("&");datastr="";for(a=0;a<b.length;a++){var c=b[a].split("=");"access_token"==c[0]?c[1]=GoogleReader.access_token:"T"==c[0]&&(c[1]=GoogleReader.api_token);
datastr+=c[0]+"="+c[1]+"&"}return datastr}};
