var divnames=["#addfeedsdiv","#myfeedsdiv","#readerviewdiv"],modes={addFeedsMode:0,myFeedsMode:1,readFeedMode:2,currentMode:0,initialise:function(){modes.switchToMode(0)},switchToMode:function(a){modes.currentMode=a;for(i=0;3>i;i++)i!=a&&$(divnames[i]).fadeOut("slow",function(){$(divnames[a]).is(":hidden")&&$(divnames[a]).show(function(){$(divnames[a]).fadeIn("slow",function(){$(divnames[a]).css("visibility","visible")})})})}};
function switchToMyFeeds(){if(modes.currentMode!=modes.myFeedsMode){var a=modes.currentMode;modes.currentMode=modes.myFeedsMode;Reader.resetState();$(divnames[a]).fadeOut("medium",function(){$("#myfeedsdiv").css("visibility","visible").show("fast",function(){$("myfeedsdiv").fadeIn("slow")})});$("#slider").empty();$("#rdrheadl li").not("#headlactions").remove()}}
function switchToAddFeeds(){if(modes.currentMode!=modes.addFeedsMode){var a=modes.currentMode;modes.currentMode=modes.myFeedsMode;Reader.resetState();$(divnames[a]).fadeOut("medium",function(){$("#addfeedsdiv").show("fast",function(){$("#addfeedsdiv").css("visibility","visible");$("addfeedsdiv").fadeIn("slow")})});$("#slider").empty();$("#rdrheadl li").not("#headlactions").remove()}}
function display_message(){$('<div class="quick-alert">Alert! Watch me before it\'s too late!</div>').insertAfter($(this)).fadeIn("slow").animate({opacity:1},3E3).fadeOut("slow",function(){$(this).remove()})}function getDomain(a){"/"!=a.substr(-1)&&(a+="/");var b=/(http:\/\/[^\/]+)/i.exec(a);return b&&1<b.length?b[1]:a}
function switchToLoadingView(a){a?($("#hprev").hide(),$("#hnext").hide(),$("#headlactions").find("img").show()):(0==parseInt($("#rdrheadl").attr("startindex"))&&$("#hprev").hide(),$("#hnext").show(),$("#headlactions").find("img").hide())}
function showSubscribedFeed(a){$(".caption",a).html("You are subscribed to "+$(a).find("img").attr("title")+'<br><img class="subscbdimg" src="img/done.png">');$(".caption",a).animate({opacity:1,"margin-top":-60},200);$("img",a).animate({opacity:0.1},200);$(".subscbdimg").animate({opacity:1},200)}
function showUnsubscribedFeed(a){$(".caption",a).html("Click me to subscribe to "+$("img",a).attr("title"));$(".caption",a).stop(0,!0,!0).animate({opacity:0},200);$("img",a).stop(0,!0,!0).animate({opacity:1},200)}function showMessage(a){$("#error-message").fadeOut("fast",function(){$(this).html(a)}).fadeIn().delay(2E3).fadeOut("fast",function(){$(this).html("Click on the feed from the categories given below or enter the URL of the desired feed of your wish")}).fadeIn()}
function continueLocal(){$("#loader").fadeOut(1E3);$("#loadercontainer").fadeOut(1E3);$(".scrollable").css("opacity",1)}function showProgress(a,b){$("#syncProgressBar").attr("value")||$("#syncProgressBar").attr("value",0);if(!0==b){var c=parseInt($("#syncProgressBar").attr("value"));$("#syncProgressBar").attr("value",parseInt(a)+c)}else $("#syncProgressBar").attr("value",a)}function showLoaderMessage(a){$("#loader").find("p").html(a)}
function addContextMenu(){pokki.resetContextMenu();pokki.addContextMenuItem("Logout","logoutbtn");pokki.addContextMenuItem("Mark All As Read","markallasread")}function hideLogoutPopup(){$("#popupbox").html("You have been logged out successfully").delay(1E3).animate({opacity:0},1E3,function(){$("#popupbox").css("display","none")})}
function showLogoutPopup(){$("#popupbox").html("Do you want to delete all existing Subscriptions ?<div class='button' onClick='Reader.logout(true);'>Yes</div><div class='button' onClick='Reader.logout(false);'>No</div>").css("display","block").animate({opacity:1},100,function(){})};
