try{pokki.isPopupShown()}catch(e$$10){pokki={addEventListener:function(a,c){this.events=this.events?this.events:{};this.events[a]||(this.events[a]=[]);this.events[a].push(c)},openPopup:function(){},closePopup:function(){},setPopupClientSize:function(){},isPopupShown:function(){return!0},openURLInDefaultBrowser:function(a){window.open(a)},setIconBadge:function(a){this.badge||(this.badge=document.createElement("div"),this.badge.style.position="absolute",this.badge.style.top="10px",this.badge.style.left=
"10px",this.badge.style.backgroundColor="#000000",this.badge.style.color="#ffffff",this.badge.style.opacity=0,this.badge.style.height="14px",this.badge.style.width="14px",this.badge.style.padding="3px",this.badge.style.lineHeight="10px",this.badge.style.border="2px solid #ffffff",this.badge.style.textAlign="center",this.badge.style.font='normal 11px "lucida grande"',this.badge.style.borderRadius="14px",this.badge.style.boxShadow="1px 1px 3px #333",this.badge.style["-webkit-transition"]="all 250ms ease-in",
pokki.is_popup?document.body.appendChild(this.badge):parent.document.body.appendChild(this.badge));99<a&&(a=99);this.badge.innerHTML=a;this.badge.style.opacity=1},removeIconBadge:function(){this.badge&&(this.badge.style.opacity=0)},rpc:function(a){pokki.is_popup?eval("pokki.backgroundWin.contentWindow.window."+a):eval("parent."+a)},showWebSheet:function(a,c,b,f){this.window=window.open(a,"_blank","height="+b+",width="+c);var e=a,d=this.window,g=this;this.interval=setInterval(function(){d.location.href&&
(e!=d.location.href&&"about:blank"!=d.location.href)&&(e=d.location.href,f&&(f(e)||g.hideWebSheet()))},100)},hideWebSheet:function(){this.window&&(this.window.close(),this.window=!1,clearInterval(this.interval))},setWebSheetSize:function(a,c){this.window&&this.window.resizeTo(a,c)},clearWebSheetCookies:function(){},getScrambled:function(a){if(pokki.manifestData)for(var c=pokki.manifestData.scrambled_data,b=0;b<c.length;b++)if(c[b].key==a)return c[b].value;return""},scramble:function(a){return a},
descramble:function(a){return a},addContextMenuItem:function(a,c){this.context_menu||(this.context_menu=document.createElement("ul"),this.context_menu.style.position="absolute",this.context_menu.style.top="10px",this.context_menu.style.listStyle="none",this.context_menu.style.right="10px",this.context_menu.style.backgroundColor="#ffffff",this.context_menu.style.color="#333",this.context_menu.style.opacity=0,this.context_menu.style.border="1px solid #d7d7d7",this.context_menu.style.textAlign="left",
this.context_menu.style.font='normal 11px "lucida grande"',this.context_menu.style.borderRadius="3px",this.context_menu.style.boxShadow="rgba(0,0,0,0.4) 0px 1px 2px",this.context_menu.style["-webkit-transition"]="all 250ms ease-in",pokki.is_popup?document.body.appendChild(this.context_menu):parent.document.body.appendChild(this.context_menu));var b=document.createElement("li");b.style.padding="5px";b.style.cursor="pointer";""!=this.context_menu.innerHTML&&(b.style.borderTop="1px solid #d7d7d7");b.innerHTML=
a;b.addEventListener("click",function(){pokki.is_popup?pokki.events&&pokki.events.context_menu&&pokki.events.context_menu(c):parent.pokki.events&&parent.pokki.events.context_menu&&parent.pokki.events.context_menu(c)});this.context_menu.appendChild(b);this.context_menu.style.opacity=1},resetContextMenu:function(){this.context_menu&&(this.context_menu.innerHTML="",this.context_menu.style.opacity=0)}},pokki.is_popup=0<location.href.search("background.html")?!1:!0,pokki.is_popup&&(pokki.backgroundWin=
document.createElement("iframe"),pokki.backgroundWin.src="background.html",pokki.backgroundWin.name="background",pokki.backgroundWin.width=1,pokki.backgroundWin.height=1,pokki.backgroundWin.addEventListener("load",function(){if(pokki.events){if(pokki.events.popup_showing)for(var a=0;a<pokki.events.popup_showing.length;a++)pokki.events.popup_showing[a]();pokki.events.popup_shown&&setTimeout(function(){for(var a=0;a<pokki.events.popup_showing.length;a++)pokki.events.popup_shown[a]()},1E3)}},!1),window.addEventListener("load",
function(){document.body.appendChild(pokki.backgroundWin)},!1)),window.addEventListener("load",function(){var a=new XMLHttpRequest;a.open("GET","manifest.json",false);a.send();pokki.manifestData=JSON.parse(a.responseText)},!1)};
